import '../scss/globals.scss';
import { Inter } from 'next/font/google';
import { I18nextProvider } from 'react-i18next';
import i18nConfig from '../../i18n-config';
import React from 'react';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" suppressHydrationWarning={true}>
      <body className={inter.className}>
        <I18nextProvider i18n={i18nConfig} defaultNS={'translation'}>
          {children}
        </I18nextProvider>
      </body>
    </html>
  );
}

export default RootLayout;
